# Generated by Django 3.2.3 on 2022-12-14 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20221214_2202'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
